# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jemoji
  
# Site settings
title: "Gsong's Blog"
description: > # this means to ignore newlines until "email:"
   사는 이야기 조금, 개발 이야기 약간

email: realgsong@gmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cover_background.png"

name: 'Ki Sung Bae'
author: 'Ki Sung Bae'
author_image: "/assets/images/author.png"

paginate:	5

url: "http://gsong.pe.kr" # the base hostname & protocol for your site
feedurl: "http://feeds.feedburner.com/GsongsBlog"
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/realgsong
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/realgsong
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/realgsong
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

# Social meta tags
timezone:       "Asia/Seoul"
locale:         "ko_kr"
social_author:
  facebook:     realgsong
  twitter:      realgsong
  google_plus:  realgsong
fb_admins:      realgsong
fb_appid:       668082886626649
production_url: "http://gsong.pe.kr"
